name: Deploy To Netlify
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify Build
        run: |
          # Adding a sleep ensures GitHub's API has updated before Netlify fetches
          sleep 5
          curl -X POST -d "{}" "https://api.netlify.com/build_hooks/${{ secrets.NETLIFY_BUILD_HOOK }}?trigger_branch=master&trigger_title=GA+Push+$(date +%F)"